[[section-system-scope-and-context]]
== Область дії системи та її контекст


[role="arc42help"]
****
.Зміст
Область дії системи та її контекст - як випливає з назви, відмежовують вашу систему (тобто вашу область) від усіх її партнерів по спілкуванню (сусідні системи та користувачі, тобто контекст вашої системи).  Таким чином, вони визначають зовнішні інтерфейси.

Якщо необхідно, відмежуйте бізнес-контекст (специфічні вхідні та вихідні данні домену) від технічного контексту (канали, протоколи, апаратне забезпечення).

.Мотивація
Інтерфейси домену та технічні інтерфейси для комунікаційних партнерів є одними з найважливіших аспектів вашої системи.  Переконайтеся, що ви їх повністю розумієте.

.Форма
Різноманітні варіанти:

* Контекстні діаграми
* Списки комунікаційних партнерів та їх інтерфейси.


.Додаткова інформація

Див. https://docs.arc42.org/section-3/[Контекст і область дії] дії в документації arc42.

****


=== Бізнес контекст

[role="arc42help"]
****
.Зміст
Специфікація *всіх* комунікаційних партнерів (користувачів, ІТ-систем, …​) з поясненнями вхідних і вихідних даних або інтерфейсів, що стосуються конкретного домену.  За бажанням ви можете додати специфічні для домену формати або протоколи зв’язку.

.Мотивація
Усі зацікавлені сторони повинні розуміти, якими даними обмінюються із середовищем системи.

.Форма
Різноманітні діаграми, які показують систему як чорний ящик і визначають інтерфейси домену для партнерів по спілкуванню.

Як альтернативу (або додатково) можна використовувати таблицю.  Заголовок таблиці – це ім’я вашої системи, три стовпці містять ім’я комунікаційного партнера, вхідні та вихідні данні.

****

**<Діаграма або таблиця>**

**<опціонально: Пояснення інтерфейсів зовнішнього домену>**

=== Технічний контекст

[role="arc42help"]
****
.Зміст
Технічні інтерфейси (канали та засоби передачі), що з’єднують вашу систему з її середовищем.  Крім того, відображення вводу/виводу, специфічного для домену, на канали, тобто пояснення щодо того, для якого вводу/виводу, який канал використовується.

.Мотивація
Багато зацікавлених сторін приймають архітектурні рішення на основі технічних інтерфейсів між системою та її контекстом.  Особливо розробники інфраструктури або апаратного забезпечення вирішують ці технічні інтерфейси.

.Форма
Наприклад  діаграма розгортання UML, що описує канали до сусідніх систем, разом із таблицею відображення, що показує зв’язки між каналами та вводом/виводом.

****

**<Діаграма або таблиця>**

**<опціонально: Пояснення технічних інтерфейсів>**

**<Зіставлення вхідних/вихідних даних з каналами>**
