ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Рантайм представлення


[role="arc42help"]
****
.Зміст
Рантайм представлення описує конкретну поведінку та взаємодію будівельних блоків системи у формі сценаріїв із таких областей:

* важливі випадки використання або функції: як їх виконують будівельні блоки?
* взаємодії на критично важливих зовнішніх інтерфейсах: як будівельні блоки співпрацюють з користувачами та сусідніми системами?
* експлуатація та управління: запуск, старт, зупинка
* сценарії помилок і винятків

Примітка: Основним критерієм вибору можливих сценаріїв (послідовностей, робочих процесів) є їх *архітектурна релевантність*. *Не* важливо описувати велику кількість сценаріїв. Краще задокументуйте репрезентативний вибір.

.Мотивація
Ви повинні розуміти, як (примірники) будівельних блоків вашої системи виконують свою роботу та спілкуються під час виконання.
Ви в основному фіксуватимете сценарії у своїй документації, щоб повідомити свою архітектуру зацікавленим сторонам, які менше бажають або не вміють читати та розуміти статичні моделі (представлення будівельних блоків, представлення розгортання).

.Форма
Існує багато позначень для опису сценаріїв, напр.

* нумерований список кроків (натуральною мовою)
* діаграми діяльності або блок-схеми
* sequence diagrams
* BPMN або EPC (ланцюги процесів подій)
* машини стану
* ...


.Додаткова інформація

Див. https://docs.arc42.org/section-6/[Представлення часу виконання] в документації arc42.

****

=== <Сценарій часу виконання 1>


* _<вставте діаграму виконання або текстовий опис сценарію>_
* _<вставте опис помітних аспектів взаємодії між
екземплярами будівельних блоків, зображеними на цій діаграмі.>_

=== <Сценарій часу виконання 2>

=== ...

=== <Сценарій часу виконання n>
