ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]


== Представлення розгортання

ifdef::arc42help[]
[role="arc42help"]
****
.Зміст
Представлення розгортання описує:

 1. технічну інфраструктуру, що використовується для виконання вашої системи, з такими елементами інфраструктури, як географічні розташування, середовища, комп’ютери, процесори, канали та топології мережі, а також інші елементи інфраструктури та

2. зіставлення будівельних блоків (програмного забезпечення) з елементами інфраструктури.

Часто системи виконуються в різних середовищах, напр. середовище розробки, середовище тестування, середовище виробництва. У таких випадках ви повинні документувати всі відповідні середовища.

Особливо задокументуйте представлення розгортання, якщо ваше програмне забезпечення виконується як розподілена система з кількома комп’ютерами, процесорами, серверами чи контейнерами або коли ви проектуєте та створюєте власні апаратні процесори та мікросхеми.

З точки зору програмного забезпечення достатньо охопити лише ті елементи інфраструктури, які необхідні для демонстрації розгортання ваших будівельних блоків. Архітектори апаратного забезпечення можуть вийти за рамки цього й описати інфраструктуру з будь-яким рівнем деталізації, який вони потребують.

.Мотивація
Програмне забезпечення не працює без апаратного забезпечення.
Ця базова інфраструктура може і буде впливати на систему та/або деякі наскрізні поняття. Тому необхідно знати інфраструктуру.

.Форма

Можливо, діаграма розгортання найвищого рівня вже міститься в розділі 3.2. як
технічний контекст із вашою власною інфраструктурою як ОДИН black box. У цьому розділі можна
маштабуватіся у цей black box за допомогою додаткових схем розгортання:

* UML пропонує діаграми розгортання, щоб висловити це бачення. Використовуйте його, ймовірно, із вкладеними діаграмами,
коли ваша інфраструктура складніша.
* Якщо ваші (апаратні) стейкхолдери віддають перевагу іншим типам діаграм, а не діаграмі розгортання, дозвольте їм використовувати будь-який вид, який здатний показати вузли та канали інфраструктури.


.Додаткова інформація

Див. https://docs.arc42.org/section-7/[Представлення розгортання] в документації arc42.

****
endif::arc42help[]

=== Інфраструктура Рівень 1

ifdef::arc42help[]
[role="arc42help"]
****
Опишіть (зазвичай у вигляді діаграм, таблиць і тексту):

* розповсюдження системи на декілька місць, середовищ, комп’ютерів, процесорів, .., а також фізичні з’єднання між ними
* важливі обґрунтування або мотивації цієї структури розгортання
* характеристики якості та/або продуктивності цієї інфраструктури
* відображення програмних артефактів на елементи цієї інфраструктури

Для кількох середовищ або альтернативних розгортань, будь ласка, скопіюйте та адаптуйте цей розділ arc42 для всіх відповідних середовищ.
****
endif::arc42help[]

_**<Оглядова діаграма>**_

Мотивація::

_<пояснення в текстовій формі>_

Характеристики якості та/або ефективності::

_<пояснення в текстовій формі>_

Відображення будівельних блоків в інфраструктурі::
_<опис відображення>_


=== Інфраструктура Рівень 2

ifdef::arc42help[]
[role="arc42help"]
****
Тут можна включити внутрішню структуру (деяких) елементів інфраструктури з рівня 1.

Будь ласка, скопіюйте структуру з рівня 1 для кожного вибраного елемента.
****
endif::arc42help[]

==== _<Інфраструктурний Елемент 1>_

_<діаграма + пояснення>_

==== _<Інфраструктурний Елемент 2>_

_<діаграма + пояснення>_

...

==== _<Інфраструктурний Елемент n>_

_<діаграма + пояснення>_
