[[розділ-проектні-рішення]]
== Архітектурні рішення


[role="arc42help"]
****
.Зміст
Важливі, дорогі, великомасштабні або ризиковані архітектурні рішення, включаючи причини.
Під «рішеннями» ми маємо на увазі вибір однієї альтернативи на основі заданих критеріїв.

Будь ласка, вирішуйте на свій розсуд, чи потрібно документувати архітектурне рішення
тут, у цьому центральному розділі, чи краще задокументувати це локально
(наприклад, у white box шаблоні одного будівельного блоку).

Уникайте надмірності.
Зверніться до розділу 4, де ви вже зафіксували найважливіші рішення вашої архітектури.

.Мотивація
Зацікавлені сторони вашої системи повинні мати можливість зрозуміти та відстежити ваші рішення.

.Форма
Різні варіанти:

* ADR ((https://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions[Запис архітектурних рішень])) для кожного важливого рішення
* Список або таблиця, упорядкована за важливістю та наслідками або:
* детальніше у вигляді окремого розділу на кожне рішення

.Додаткова інформація

Див. https://docs.arc42.org/section-9/[Архітектурні рішення] в документації arc42.
Там ви знайдете посилання та приклади щодо ADR.

****
