ifndef::imagesdir[:imagesdir: ../images]

[[розділ-якість-сценарії]]
== Вимоги до якості


ifdef::arc42help[]
[role="arc42help"]
****

.Зміст
Цей розділ містить усі вимоги до якості у вигляді дерева якості зі сценаріями. Найважливіші з них уже описано в розділі 1.2. (цілі якості)

Тут ви також можете охопити вимоги до якості з меншим пріоритетом,
які не створюватимуть високих ризиків, коли вони не будуть повністю досягнуті.

.Мотивація
Оскільки вимоги до якості матимуть великий вплив на архітектуру
рішення, які ви повинні знати для кожної зацікавленої сторони, що для них дійсно важливо,
конкретно і вимірювано.


.Додаткова інформація

Див. https://docs.arc42.org/section-10/[Вимоги до якості] в документації arc42.

****
endif::arc42help[]

=== Дерево якості

ifdef::arc42help[]
[role="arc42help"]
****
.Зміст
Дерево якості (як визначено в ATAM – Метод аналізу компромісів архітектури) зі сценаріями якості/оцінки у вигляді листків.

.Мотивація
Деревоподібна структура з пріоритетами надає огляд для інколи великої кількості вимог до якості.

.Форма
Дерево якості – це загальний огляд цілей і вимог до якості:

* деревоподібне уточнення терміна «якість». Використовуйте «якість» або «корисність» як корінь
* розумова карта з категоріями якості як основними гілками

У будь-якому випадку дерево має містити посилання на сценарії наступного розділу.


****
endif::arc42help[]

=== Сценарії якості

ifdef::arc42help[]
[role="arc42help"]
****
.Зміст
Конкретизація (іноді нечітких або неявних) вимог до якості за допомогою сценаріїв (якості).

Ці сценарії описують, що має статися, коли в систему надходить подразник.

Для архітекторів важливі два види сценаріїв:

* Сценарії використання (також звані прикладними сценаріями або сценаріями використання) описують реакцію системи на певний стимул, під час виконання. Це також включає сценарії, які описують ефективність або продуктивність системи. Приклад: система реагує на запит користувача протягом однієї секунди.
* Сценарії змін описують модифікацію системи або її найближчого оточення. Приклад: реалізовано додаткові функції або змінено вимоги до атрибута якості.

.Мотивація
Сценарії конкретизують вимоги до якості та дозволяють
легше виміряти або вирішити, чи виконуються вони.

Особливо, коли ви хочете оцінити свою архітектуру за допомогою таких методів як
ATAM, вам потрібно описати свої цілі щодо якості (з розділу 1.2)
точніше, до рівня сценаріїв, які можна обговорювати та оцінювати.

.Форма
Табличний або довільний текст.
****
