ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Visão de Tempo de Execução


ifdef::arc42help[]
[role="arc42help"]
****
.Conteúdo
A visão de tempo de execução descreve o comportamento concreto e as interações dos blocos de construção do sistema na forma de cenários das seguintes áreas:

* casos de uso ou recursos importantes: como os blocos de construção os executam?
* interações em interfaces externas críticas: como os blocos de construção cooperam com os usuários e sistemas vizinhos?
* operação e administração: lançamento, inicialização, parada
* cenários de erro e exceção

Observação: O principal critério para a escolha de cenários possíveis (sequências, fluxos de trabalho) é sua *relevância arquitetural*. *Não* é importante descrever um grande número de cenários. Você deve documentar uma seleção representativa.

.Motivação
Você deve entender como (instâncias de) blocos de construção do seu sistema realizam seu trabalho e se comunicam em tempo de execução.
Você capturará principalmente cenários em sua documentação para comunicar sua arquitetura às partes interessadas que estão menos dispostas ou capazes de ler e entender os modelos estáticos (visão de bloco de construção, visão de implantação).

.Forma
Há muitas notações para descrever cenários, por exemplo,

* lista numerada de etapas (em linguagem natural)
* diagramas de atividade ou fluxogramas
* diagramas de sequência
* BPMN ou EPCs (cadeias de processos de eventos)
* máquinas de estado
* ...

.Mais informações


Consulte https://docs.arc42.org/section-6/[Runtime View] na documentação do arc42.

****
endif::arc42help[]

=== <Cenário de Tempo de Execução 1>

* _<inserir diagrama de tempo de execução ou descrição textual do cenário>_
* _<inserir descrição dos aspectos notáveis ​​das interações entre as
instâncias do bloco de construção descritas neste diagrama.>_

=== <Cenário de Tempo de Execução 2>

=== ...

=== <Cenário de Tempo de Execução n>
