[[section-introduction-and-goals]]
== Введение и цели

[role="arc42help"]
****
Опишите релевантные требования и движущие факторы, которые должны быть приняты во внимание командой разработки. Они включают в себя

* основные бизнес-цели, основные возможности системы и функциональные требования к системе
* качественные цели для архитектуры
* основных стейкхолдеров и их ожидания от системы
****

=== Обзор требований

[role="arc42help"]
****
.Содержание
Краткое описание функциональных требований, движущих сил, выжимка (или обобщенное описание) общих
требований к системе. Ссылки на документы с требованиями с указанием версии и расположения документов (если, конечно, они у вас есть).

.Мотивация
С точки зрения конечных пользователей, система создается или дорабатывается, чтобы 
улучшить поддержку бизнес-активностей и/или для улучшения качества системы в целом.

.Форма
Краткое текстовое описание, возможно, в формате таблицы со сценариями использования.
Старайтесь быть лаконичными. Необходимо соблюсти баланс читабельности и избыточности, 
не надо переписывать здесь весь список требований из связанных документов.
****


=== Качественные цели архитектуры

[role="arc42help"]
****
.Содержание
Важнейшие три (максимум пять) характеристик качества архитектуры, достижение которых имеет первостепенное значение для основных стейкхолдеров.
В данном контексте имеются в виду именно целевые атрибуты качества архитектуры, а не проекта в целом -- они не обязательно идентичны друг другу.

.Мотивация
Вы должны знать о качественных целях, которые наиболее важны для ваших стейкхолдеров, так как они будут оказывать влияние
на фундаметальные архитектурные решения. Убедитесь, что вы точно описали ожидаемые результаты, старайтесь избегать жаргонизмов и баззвордов.
Если вы как архитектор не знаете, как будет оцениваться качество вашей работы, то как вы будете её выполнять?

.Форма
Таблица с атрибутами качества и сценариями описания их характеристик, в порядке приоритета достижения.

****

=== Ключевые участники (стейкхолдеры)
[role="arc42help"]
****
.Содержание
Явное описание стейкхолдеров системы, в том числе всех людей, ролей или организаций, которые:

* должны знать итоговую архитектуру решения
* должны быть уверены в её качестве
* должны работать с архитектурой системы или с её кодом
* должны использовать архитектурную документацию в своей работе
* должны принимать решения о разработке системы или её развитии

.Мотивация
Вы должны знать знать всех, кто вовлечен в процесс разработки системы или будет каким-то образом затронут её функционированием.
Иначе, вы можете столкнуться с неприятными сюрпризами в процессе дальнейшей разработки системы.
Именно эти стейкхолдеры определяют степень и уровень детализации вашей работы и её результатов.

.Форма
Таблица с названиями ролей/именами участников вместе с их ожиданиями от системы, её архитектуры и документации.
****
[options="header",cols="1,2,2"]
|===
|Роль/Имя|Контактные данные|Ожидания
| _<Роль-1>_ | _<Контактные данные-1_> | _<Ожидание-1>_
| _<Роль-2>_ | _<Контактные данные-2>_ | _<Ожидание-2>_
|===
