ifndef::imagesdir[:imagesdir: ../images]

[[section-architecture-constraints]]
== Архитектурные ограничения


[role="arc42help"]
****
.Содержание
Любое требование, ограничивающее архитекторов программного обеспечения в их свободе проектирования и решений по реализации или в принятии решений о процессе разработки. Эти ограничения иногда выходят за рамки отдельных систем и действительны для целых организаций и компаний.

.Мотивация
Архитекторы должны точно знать, где они свободны в своих проектных решениях, а где должны придерживаться ограничений.
С ограничениями всегда нужно иметь дело; хотя они могут быть предметом переговоров.

.Форма
Простые таблицы ограничений с пояснениями.
При необходимости вы можете разделить их на
технические ограничения, организационные и политические ограничения и
соглашения (например, рекомендации по программированию или управлению версиями, документация или соглашения о наименованиях)


.Дальнейшая информация

Смотрите https://docs.arc42.org/section-2/[Архитектурные ограничения] в документации arc42.

****
