ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Context and Scope


[role="arc42help"]
****
.Содержание

Context and scope - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

Контекст и область действия — как следует из названия — разграничивают вашу систему (то есть область действия) от всех ее коммуникационных партнеров.
(соседние системы и пользователи, т.е. контекст вашей системы). Таким образом, он определяет внешние интерфейсы.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

При необходимости различайте бизнес-контекст (специфические для предметной области входы и выходы) и технический контекст (каналы, протоколы, аппаратное обеспечение).

.Мотивация
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Форма
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.

Различные варианты:

* Контекстные диаграммы
* Списки коммуникационных партнеров и их интерфейсов.

.Дальнейшая информация

Смотрите https://docs.arc42.org/section-3/[Context and Scope] в документации arc42.

****


=== Business Context

[role="arc42help"]
****
.Содержание
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

Спецификация *всех* коммуникационных партнеров (пользователи, ИТ-системы, ...) с пояснениями входных и выходных данных или интерфейсов, специфичных для предметной области.
При желании вы можете добавить специфичные для домена форматы или протоколы связи.

.Мотивация
All stakeholders should understand which data are exchanged with the environment of the system.

Все заинтересованные стороны должны понимать, какими данными происходит обмен со средой системы.

.Форма
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.

Все виды диаграмм, изображающих систему в виде черного ящика и определяющих интерфейсы домена для коммуникационных партнеров.

В качестве альтернативы (или дополнительно) можно использовать таблицу.
Заголовок таблицы — это имя вашей системы, три столбца содержат имя партнера по связи, входы и выходы.

****

**<Диаграмма или таблица>**

**<опционально: объяснение внешних доменных интерфейсов>**

=== Технический контекст

[role="arc42help"]
****
.Содержание
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation which I/O uses which channel.

Технические интерфейсы (каналы и среды передачи), связывающие вашу систему с окружающей средой. Кроме того, сопоставление ввода/вывода, специфичного для предметной области, с каналами, то есть объяснение, какой ввод/вывод использует какой канал.

.Мотивация
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

Многие заинтересованные стороны принимают архитектурные решения на основе технических интерфейсов между системой и ее контекстом. Особенно разработчики инфраструктуры или оборудования решают эти технические интерфейсы.

.Форма
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

Например. Диаграмма развертывания UML, описывающая каналы к соседним системам,
вместе с таблицей сопоставления, показывающей взаимосвязь между каналами и вводом/выводом.

****

**<Диаграмма или таблица>**

**<опционально: Пояснения к техническим интерфейсам>**

**<Сопоставление ввода/вывода с каналами>**
