ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Контекст и рамки


[role="arc42help"]
****
.Содержание

Контекст и область действия — как следует из названия — разграничивают вашу систему (ее рамки) от всех партнеров с которыми она коммуницирует (соседние системы и пользователи, т.е. контекст вашей системы). Таким образом, он определяет внешние интерфейсы.

При необходимости различайте бизнес-контекст (специфические для предметной области входы и выходы) и технический контекст (каналы, протоколы, аппаратное обеспечение).

.Мотивация
Интерфейсы домена и технические интерфейсы для коммуникационных партнеров являются одними из наиболее важных аспектов вашей системы. Убедитесь, что вы их полностью понимаете.

.Форма
Различные варианты:

* Контекстные диаграммы
* Списки коммуникационных партнеров и их интерфейсов.

.Дальнейшая информация

Смотрите https://docs.arc42.org/section-3/[Context and Scope] в документации arc42.

****


=== Бизнес контекст

[role="arc42help"]
****
.Содержание
Спецификация *всех* коммуникационных партнеров (пользователи, ИТ-системы, ...) с пояснениями входных и выходных данных или интерфейсов, специфичных для предметной области.
При желании вы можете добавить специфичные для домена форматы или протоколы связи.

.Мотивация
Все заинтересованные стороны должны понимать, какими данными система обменивается со средой.

.Форма
Все виды диаграмм, изображающих систему в виде черного ящика и определяющих интерфейсы домена для коммуникационных партнеров.

В качестве альтернативы (или дополнительно) можно использовать таблицу.
Заголовок таблицы — это имя вашей системы, три столбца содержат имя партнера, с которым происходит коммуникация, входы и выходы.

****

**<Диаграмма или таблица>**

**<необязательно: объяснение внешних доменных интерфейсов>**

=== Технический контекст

[role="arc42help"]
****
.Содержание
Технические интерфейсы (каналы и среды передачи), связывающие вашу систему с окружающей средой. Кроме того, сопоставление ввода/вывода, специфичного для предметной области, с каналами, то есть объяснение, какой ввод/вывод использует какой канал.

.Мотивация
Многие заинтересованные стороны принимают архитектурные решения на основе технических интерфейсов между системой и ее контекстом. Зачастую разработчики инфраструктуры или оборудования выбирают эти технические интерфейсы.

.Форма
Например, диаграмма развертывания UML, описывающая каналы к соседним системам,
вместе с таблицей сопоставления, показывающей взаимосвязь между каналами и вводом/выводом.

****

**<Диаграмма или таблица>**

**<необязательно: Пояснения к техническим интерфейсам>**

**<Сопоставление ввода/вывода с каналами>**
