[[section-system-scope-and-context]]
== Границы и окружение системы

[role="arc42help"]
****
.Содержание
Границы и окружение по определению отделяют вашу систему от всех взаимодействующих с ней партнёров
(соседних систем и пользователей). Именно через них определяются внешние интерфейсы.

При необходимости, разделите окружение системы на бизнес контекст (специфичные доменные входы/выходы системы) и технический контекст (каналы связи,протоколы, техническое обеспечение).

.Мотивация
Доменные и технические интерфейсы для взаимодействия с партнёрами входят в число наиболее критических аспектов вашей системы. Убедитесь,
что вы полностью их проработали.

.Форма
Можно использовать различные варианты:

* Контекстные диаграммы
* Список взаимодействующих партнёров и их интерфейсы
****

=== Бизнес контекст
[role="arc42help"]
****
.Содержание
Спецификация *всех* участников взаимодействия с системой (пользователи, другие IT-системы, ...) с описание специфических для вашего домена входных и 
выходных данных или интерфейсов.
Опционально вы можете добавить доменные форматы или протоколы взаимодействия.

.Мотивация
Все стейкхолдеры должны понимать, какими данными производится обмен на границе системы с её окружением. 

.Форма
Любые виды диаграмм, которые показывают систему в виде черного ящика и специфицируют доменные интерфейсы для участников взаимодействий.

Альтернативно (или дополнительно) можно использовать таблицу.
Заголовок -- название системы, три столбца отображают название участника взаимодействия, входные и выходные данные, соответственно.
****

**<Диаграмма или таблица>**

**<Опционально: Описание внешних доменных интерфейсов>**

=== Технический контекст
[role="arc42help"]
****
.Содержание
Технические интерфейсы (каналы и средства передачи данных), свзяывающие вашу систему с её окружением. Дополнительно стоит включить отображение
входных и выходных доменных данных на указанные каналы, то есть описание, по каким каналам передаются конкретные данные.

.Мотивация
Многие стейкхолдеры принимают свои архитектурные решения, основываясь на технических интерфейсах между системой и её окружением.
В особенности, данная информация важна для дизайна инфраструктуры или организации аппаратного обеспечения системы. 

.Форма
Например, UML диаграмма развёртывания, описывающая каналы к соседним системам. В дополнение к диаграмме необходима таблица с описанием
отображения каналов на входные и выходные данные системы

****

**<Диаграмма или таблица>**

**<Опционально: Подробное объяснение технических интерфейсов>**

**<Отображение входных и выходных данных на каналы передачи данных>**


