ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Стратегия решения


[role="arc42help"]
****
.Содержание

Краткое изложение и объяснение основных решений и стратегии, формирующих архитектуру системы. Они включают

* технологические решения
* решения о декомпозиции системы на верхнем уровне, т.е. использование архитектурного шаблона или шаблона проектирования
* решения о том, как достичь ключевых целей в области качества
* соответствующие организационные решения, т.е. выбор процесса разработки или делегирование определенных задач третьим лицам.

.Мотивация
Эти решения ложатся в основу вашей архитектуры. На них опираются многие другие более специфические решения или правила реализации.

.Форма
Объяснения таких ключевых решений должны быть короткими.

Мотивируйте решение (и почему было решено именно так)
на основе постановки задачи, целей в области качества и ключевых ограничений.
Подробности см. в следующих разделах.

.Дальнейшая информация

Смотрите https://docs.arc42.org/section-4/[Стратегия решения] в документации arc42.

****
