[[section-runtime-view]]
== Динамическое представление

[role="arc42help"]
****
.Содержание
Динамическое представление показывает конкретное поведение и взаимодействия компонентов системы друг с другом и с окружением. Сценарии 
должны включать в себя:

* важные способы использования и функции: как компоненты системы их реализуют?
* реализация критичных внешних интерфейсов: как компоненты системы взаимодействуют с пользователями и другими системами?
* обслуживание и администрирование: установка, запуск, останов, важные сценарии сопровождения
* сценарии исключительных ситуаций и обработки ошибок

Замечание: Важнейшим критерием для выбора сценариев (последовательностей, процессов) для описания является их *архитектурная значимость*. Важно не описать *максимально* возможное коилчество сценариев, а зафиксировать наиболее значимые среди них. 

.Мотивация
Вы должны понимать, как экземпляры компонентов вашей системы выполняют свою работу и взаимодействуют с окружением во время исполнения.
В основном, документирование этих сценариев необходимо для объяснения вашей архитектуры стейкхолдерам, которые не хотят или не очень хорошо понимают статические модели (компонентная модель, схема развёртывания).

.Форма
Существует несколько нотаций для описания сценариев, например:

* нумерованный список шагов (на естественном языке)
* диаграммы деятельности или блок-схемы
* диаграммы последовательности
* BPMN или EPC (событийные цепочки)
* машины состояний
* ...

****

=== Сценарий 1

* _<вставьте диаграмму или текстовое описание сценария>_
* _<вставье описание важных аспектов взаимодействия экзепляров компонент, представленных на этой схеме>_

=== Сценарий 2

=== ...

=== Сценарий n
