ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]
== Представления развертывания

[role="arc42help"]
****
Представление развертывания описывает:

1. техническую инфраструктуру, используемую для работы вашей системы, с элементами инфраструктуры, такими как географические местоположения, среды, компьютеры, процессоры, каналы и сетевые топологии, а также другие элементы инфраструктуры и

2. сопоставление строительных блоков (программного обеспечения) с этими элементами инфраструктуры.

Часто системы выполняются в разных средах, например. среда разработки, тестовая среда, продакшн.
В таких случаях вы должны задокументировать все соответствующие среды.

Особенно важно задокументировать представление развертывания, если ваше программное обеспечение выполняется в виде распределенной системы с более чем одним компьютером, процессором, сервером или контейнером; или когда вы проектируете и создаете свои собственные аппаратные процессоры и микросхемы.

С точки зрения программного обеспечения достаточно зафиксировать только те элементы инфраструктуры, которые необходимы для демонстрации развертывания ваших строительных блоков.
Архитекторы аппаратного обеспечения могут пойти дальше и описать инфраструктуру с любым уровнем детализации, который им необходим.

.Мотивация
Программное обеспечение не работает без аппаратного обеспечения.
Эта базовая инфраструктура может и будет влиять на систему и/или некоторые сквозные (cross-cutting) концепции.
Поэтому необходимо знать инфраструктуру.

.Форма
Maybe a highest level deployment diagram is already contained in section 3.2. as technical context with your own infrastructure as ONE black box.
In this section one can zoom into this black box using additional deployment diagrams:

Возможно, схема развертывания самого высокого уровня уже содержится в разделе 3.2. в виде технического контекста с собственной инфраструктурой, описанной ОДНИМ черным ящиком.
В этом разделе можно раскрыть этот черный ящик, используя дополнительные диаграммы развертывания:

* UML предлагает диаграммы развертывания, чтобы выразить это представление.
Используйте его, возможно, с вложенными диаграммами, в случае если ваша инфраструктура более сложна.
* Если заинтересованные стороны (связанные с аппаратным обеспечением) предпочитают другие виды диаграмм, а не диаграмму развертывания, позвольте им использовать любой вид, способный отображать узлы и каналы инфраструктуры.

.Дальнейшая информация
Смотри https://docs.arc42.org/section-7/[Deployment View] в документации arc42.

****

=== Infrastructure Level 1

[role="arc42help"]
****
Describe (usually in a combination of diagrams, tables, and text):

* distribution of a system to multiple locations, environments, computers, processors, .., as well as physical connections between them
* important justifications or motivations for this deployment structure
* quality and/or performance features of this infrastructure
* mapping of software artifacts to elements of this infrastructure

For multiple environments or alternative deployments please copy and adapt this section of arc42 for all relevant environments.

Опишите (обычно в комбинации диаграмм, таблиц и текста):

* распределение системы по нескольким местоположениям, средам, компьютерам, процессорам и т. д., а также физическим соединениям между ними
* важные обоснования или мотивы для этой структуры развертывания
* характеристики качества и/или производительности этой инфраструктуры
* сопоставление программных артефактов с элементами этой инфраструктуры

Для нескольких сред или альтернативных развертываний скопируйте и адаптируйте этот раздел arc42 для всех соответствующих сред.
****

_**<Overview Diagram>**_

Motivation::

_<объяснение в текстовом виде>_

Quality and/or Performance Features::

_<объяснение в текстовом виде>_

Mapping of Building Blocks to Infrastructure::
_<description of the mapping>_

=== Infrastructure Level 2

[role="arc42help"]
****
Here you can include the internal structure of (some) infrastructure elements from level 1.

Please copy the structure from level 1 for each selected element.
****

==== _<Infrastructure Element 1>_

_<diagram + explanation>_

==== _<Infrastructure Element 2>_

_<diagram + explanation>_

...
==== _<Infrastructure Element n>_

_<diagram + explanation>_
