[[section-deployment-view]]


== Схема развёртывания
[role="arc42help"]
****
.Содержание
Схема развёртывания описывает:

1. Техническую инфраструктуру, используемую для работы системы с такими инфраструктурными компонентами, как географические зоны, среды, компьютеры, процессоры, каналы и сетевые топологии наряду с другими инфраструктурными элементами;

2. Отображение структурных компонентов системы на эти инфраструктурные элементы.

Часто системы работают в различных средах, например, среда разработки, среда тестирования, промышленная среда. В этом случае необходимо описать все важные среды.

В особенности, документирование схемы развёртывания необходимо, когда ваша система является распределённой и функционирует более чем на одном сервере или в одном контейнере, или же когда вы разрабатываете и конструируете свои собственные хардварные решения.

С точки зрения программного обеспечения достаточно отразить те элементы инфраструктуры, которые вам необходимы, чтобы описать развёртывание основных компонент вашего приложение. Архитекторы аппаратного обеспечения же могут пойти дальше и описывать инфраструктуру на любом уровне детализации, который они посчитают нужым.

.Мотивация
Программное обеспечение не может работать без соответствующих аппаратных ресурсов.
Эта инфраструктура может и будет влиять на вашу систему и/или какие-либо сопутствующие концепции. Следовательно, вы обязаны знать свою инфраструктуру.



****

[role="arc42help"]
****
.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence your system and/or some
cross-cutting concepts. Therefore, you need to know the infrastructure.

.Form

Maybe the highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section you will
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than the deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.
****

=== Infrastructure Level 1

[role="arc42help"]
****
Describe (usually in a combination of diagrams, tables, and text):

*  the distribution of your system to multiple locations, environments, computers, processors, .. as well as the physical connections between them
*  important justification or motivation for this deployment structure
* Quality and/or performance features of the infrastructure
*  the mapping of software artifacts to elements of the infrastructure

For multiple environments or alternative deployments please copy that section of arc42 for all relevant environments.
****

_**<Overview Diagram>**_

Motivation::

_<explanation in text form>_

Quality and/or Performance Features::

_<explanation in text form>_

Mapping of Building Blocks to Infrastructure::
_<description of the mapping>_


=== Infrastructure Level 2

[role="arc42help"]
****
Here you can include the internal structure of (some) infrastructure elements from level 1.

Please copy the structure from level 1 for each selected element.
****

==== _<Infrastructure Element 1>_

_<diagram + explanation>_

==== _<Infrastructure Element 2>_

_<diagram + explanation>_

...

==== _<Infrastructure Element n>_

_<diagram + explanation>_
