[[section-deployment-view]]


== Схема развёртывания
[role="arc42help"]
****
.Содержание
Схема развёртывания описывает:

1. Техническую инфраструктуру, используемую для работы системы с такими инфраструктурными компонентами, как географические зоны, среды, компьютеры, процессоры, каналы и сетевые топологии наряду с другими инфраструктурными элементами;

2. Отображение структурных компонентов системы на эти инфраструктурные элементы.

Часто системы работают в различных средах, например, среда разработки, среда тестирования, промышленная среда. В этом случае необходимо описать все важные среды.

В особенности, документирование схемы развёртывания необходимо, когда ваша система является распределённой и функционирует более чем на одном сервере или в одном контейнере, или же когда вы разрабатываете и конструируете свои собственные хардварные решения.

С точки зрения программного обеспечения достаточно отразить те элементы инфраструктуры, которые вам необходимы, чтобы описать развёртывание основных компонент вашего приложение. Архитекторы аппаратного обеспечения же могут пойти дальше и описывать инфраструктуру на любом уровне детализации, который они посчитают нужым.

.Мотивация
Программное обеспечение не может работать без соответствующих аппаратных ресурсов.
Эта инфраструктура может и будет влиять на вашу систему и/или какие-либо сопутствующие концепции. Следовательно, вы обязаны знать свою инфраструктуру.

.Форма
Возможно, самый верхнеуровневый вариант схемы развёртывания уже приведен в разделе 3.2 в качестве технического контекста системы,
и изображает все инфраструктурные компоненты системы в виде одного черного ящика. В этой секции документа вы должны 
детально рассмотреть этот черный ящик с помощью дополнительных схем и диаграмм:

* UML предлагает собственные представления диаграмм развёртывания. Используйте этот формат, возможно, с использованием вложенных
диаграмм для более детального описания сложных инфраструктурных компонентов.
* Если (технические) стейкхолдеры проекта предпочитают другие виды/нотации диаграмм, используйте их.

****

=== Инфраструктурный уровень 1

[role="arc42help"]
****
Опишите, используя различные вариации диаграмм, таблиц и простого текста:

* распределение системы по географическим зонам, средам исполнения, серверам, процессорам... И также опишите физические каналы взаимодействия между ними
* обоснование и мотивацию такой схемы развёртывания
* характеристики качества и/или производительности, которые обеспечивает инфраструктура
* отображение компонентов системы на элементы инфраструктуры

В случае наличия нескольких сильно различающихся сред или альтернативных вариантов развёртывания, скопируйте и заполните для них эту 
секцию шаблона
****

_**<Обзорная диаграмма>**_

Мотивация::

_<Разъяснения в текстовой форме>_

Характеристики качества и/или производительности::

_<Разъяснения в текстовой форме>_

Отображение компонентов системы на инфраструктуру::

_<Описание отображения>_

=== Инфраструктурный уровень 2
[role="arc42help"]
****
Включите в этот раздел описание внутренней структуры (некоторых) инфраструктурных элементов уровня 1, если это необходимо
****


==== _<Инфраструктурный элемент 1>_

_<Диаграмма и описание>_

==== _<Инфраструктурный элемент 2>_

_<Диаграмма и описание>_

...

==== _<Инфраструктурный элемент n>_

_<Диаграмма и описание>_
