[[section-deployment-view]]


== Схема развёртывания
[role="arc42help"]
****
.Содержание
Схема развёртывания описывает:

1. Техническую инфраструктуру, используемую для работы системы с такими инфраструктурными компонентами, как географические зоны, среды, компьютеры, процессоры, каналы и сетевые топологии наряду с другими инфраструктурными элементами;

2. Отображение структурных компонентов системы на эти инфраструктурные элементы.

Часто системы работают в различных средах, например, среда разработки, среда тестирования, промышленная среда. В этом случае необходимо описать все важные среды.

В особенности, документирование схемы развёртывания необходимо, когда ваша система является распределённой и функционирует более чем на одном сервере или в одном контейнере, или же когда вы разрабатываете и конструируете свои собственные хардварные решения.

С точки зрения программного обеспечения достаточно отразить те элементы инфраструктуры, которые вам необходимы, чтобы описать развёртывание основных компонент вашего приложение. Архитекторы аппаратного обеспечения же могут пойти дальше и описывать инфраструктуру на любом уровне детализации, который они посчитают нужым.

.Мотивация
Программное обеспечение не может работать без соответствующих аппаратных ресурсов.
Эта инфраструктура может и будет влиять на вашу систему и/или какие-либо сопутствующие концепции. Следовательно, вы обязаны знать свою инфраструктуру.

.Форма
Возможно, самый верхнеуровневый вариант схемы развёртывания уже приведен в разделе 3.2 в качестве технического контекста системы,
и изображает все инфраструктурные компоненты системы в виде одного черного ящика. В этой секции документа вы должны 
детально рассмотреть этот черный ящик с помощью дополнительных схем и диаграмм:

* UML предлагает собственные представления диаграмм развёртывания. Используйте этот формат, возможно, с использованием вложенных
диаграмм для более детального описания сложных инфраструктурных компонентов.
* Если (технические) стейкхолдеры проекта предпочитают другие виды/нотации диаграмм, используйте их.

****

=== Инфраструктурный уровень 1

[role="arc42help"]
****

****

=== Infrastructure Level 1

[role="arc42help"]
****
Describe (usually in a combination of diagrams, tables, and text):

*  the distribution of your system to multiple locations, environments, computers, processors, .. as well as the physical connections between them
*  important justification or motivation for this deployment structure
* Quality and/or performance features of the infrastructure
*  the mapping of software artifacts to elements of the infrastructure

For multiple environments or alternative deployments please copy that section of arc42 for all relevant environments.
****

_**<Overview Diagram>**_

Motivation::

_<explanation in text form>_

Quality and/or Performance Features::

_<explanation in text form>_

Mapping of Building Blocks to Infrastructure::
_<description of the mapping>_


=== Infrastructure Level 2

[role="arc42help"]
****
Here you can include the internal structure of (some) infrastructure elements from level 1.

Please copy the structure from level 1 for each selected element.
****

==== _<Infrastructure Element 1>_

_<diagram + explanation>_

==== _<Infrastructure Element 2>_

_<diagram + explanation>_

...

==== _<Infrastructure Element n>_

_<diagram + explanation>_
