ifndef::imagesdir[:imagesdir: ../images]

[[section-design-decisions]]
== Архитектурные решения


[role="arc42help"]
****
.Содержание
Важные, дорогие, крупномасштабные или рискованные архитектурные решения, включая их обоснование.
Под «решениями» мы подразумеваем выбор одной альтернативы на основе заданных критериев.

Решите сами, следует ли документировать архитектурное решение в этом центральном разделе, или лучше документировать это локально (например, в шаблоне белого ящика одного стандартного блока).

Избегайте избыточности.
Обратитесь к разделу 4, где вы уже зафиксировали наиболее важные решения вашей архитектуры.

.Мотивация
Заинтересованные лица вашей системы должны иметь возможность понять и проследить ваши решения.

.Форма
Различные варианты:

* ADR (https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Документирование архитектурных решений]) для каждого важного решения
* Список или таблица, упорядоченные по важности и последствиям или:
* подробнее в виде отдельных разделов по решению

.Дальнейшая информация

Смотри https://docs.arc42.org/section-9/[Архитектурные решения] в документации arc42.
Там вы найдете ссылки и примеры по ADR.

****
