ifndef::imagesdir[:imagesdir: ../images]

[[section-quality-scenarios]]
== Требования к качеству


[role="arc42help"]
****

.Содержание
Этот раздел содержит все требования к качеству в виде дерева качества со сценариями. Наиболее важные из них уже были описаны в разделе 1.2. (цели качества)

Здесь вы также можете зафиксировать требования к качеству с меньшим приоритетом,
не создающие высоких рисков будучи не полностью достигнутыми.

.Мотивация
Поскольку требования к качеству будут иметь большое влияние на архитектурные
решения, вы должны знать что действительно важно для каждой из заинтересованных сторон (конкретно и измеримо).

.Дальнейшая информация

Смотри https://docs.arc42.org/section-10/[Требования к качеству] в документации arc42.

****

=== Дерево качества

[role="arc42help"]
****
.Содержание
Дерево качества (как определено в ATAM — Architecture Tradeoff Analysis Method) со сценариями качества/оценки в виде листьев.

.Мотивация
Древовидная структура с приоритетами обеспечивает обзор большого количества требований к качеству.

.Форма
Дерево качества представляет собой высокоуровневый обзор целей и требований в области качества:

* древовидное уточнение термина «качество». Используйте «качество» или «полезность» в качестве корня
* майндмпеп с категориями качества в качестве основных ветвей

В любом случае дерево должно включать ссылки на сценарии следующего раздела.

****

=== Сценарии качества

[role="arc42help"]
****
.Содержание
Конкретизация (иногда расплывчатых или неявных) требований к качеству с использованием сценариев (качества).

Эти сценарии описывают, что должно произойти, когда в систему поступает стимул.

Для архитекторов важны два вида сценариев:

* Сценарии использования (также называемые сценариями приложений или сценариями вариантов использования) описывают реакцию системы во время выполнения на определенный стимул. Сюда также входят сценарии, описывающие эффективность или производительность системы. Пример: Система реагирует на запрос пользователя в течение одной секунды.
* Сценарии изменений описывают модификацию системы или ее ближайшего окружения. Пример: Реализована дополнительная функциональность или изменены требования к атрибуту качества.

.Мотивация
Сценарии конкретизируют требования к качеству и позволяют
легче измерить или решить, выполнены ли они.

Особенно, когда вы хотите оценить свою архитектуру, используя такие методы, как
ATAM вам необходимо описать ваши цели в области качества (из раздела 1.2)
точнее до уровня сценариев, которые можно обсуждать и оценивать.

.Форма
Табличный или произвольный текст.
****
