[[section-quality-scenarios]]
== Требования к атрибутам качества


[role="arc42help"]
****

.Содержание
Этот раздел должен содержать все требования к атрибутам качества системы в виде дерева качественных характеристик с описанием сценариев. 
Наиболее важные из них при этом должны быть приведены в разделе 1.2 (Целевые характеристики атрибутов качества)

Здесь вы также можете зафиксировать качественные требования с меньшим приоритетом, недостижение которых не должно привести
к большому риску.

.Мотивация
Так как качественные требования оказывают большое влияния на принятие архитектурных решений, вы должны зафиксировать качества системы,
достижение которых важно для каждого из стейкхолдеров, в конкретной и измеримой форме. 
****

=== Дерево атрибутов качества

[role="arc42help"]
****
.Содержание
Дерево атрибутов качества (также называемое ATAM - Architecture Tradeoff Analysis Method) с описанием сценариев проверки качества 
в качестве листьев.

.Мотивация
Древовидная структура с указанием приоритетов позволяет одним взглядом охватить большое количество требований к качеству.

.Форма
Дерево атрибутов качества это верхнеуровневый обзор требований и целевых характеристик качества системы:

* это раскрытие термина "качество" в древовидной форме. В качестве корня дерева используйте слово "качество" или "полезность"
* диаграмма связей с категориями качества в качестве основных ветвей

В любом случае дерево должно включать ссылка на сценарии из следующего раздела.

****

=== Сценарии проверки атрибутов качества

[role="arc42help"]
****
.Содержание
Конкретизация требований к качеству (иногда неопределенных или неявных) с использованием сценариев проверки атрибутов качества.

Эти сценарии описывают, что должно происходить с системой в случае определённых видов воздействия.

Для архитекторов особенно важны два типа сценариев:

* Сценарии использования (также называемые сценариями или вариантами использования), описывающие реакции системы на определённые действия (стимулы).
Они также включают в себя сценарии, раскрывающие эффективности и/или производительность системы. Пример: скорость реакции системы на пользовательский запрос не более одно секунды.
* Сценарии изменения, описывающие процесс модификации системы или её непостредственного окружения. Пример: Внедрение дополнительной функциональности или изменение требования к атрибуту качества.

.Мотивация
Сценарии делают требования к атрибутам качества более конкретными и детальными, что упрощает их измерение и решение, выполняются ли
конкретные требования

В особенности, если вы хотите в дальнейшем оценить свою архитектуру с использованием таких методов, как ATAM, вам необходимо описать
целевые характеристики атрибутов качества, детализируя их до уровня сценариев, которые могут быть обсуждены и оценены.

.Форма
Табличное или простое текстовое представление

****
