ifndef::imagesdir[:imagesdir: ../images]

[[section-quality-scenarios]]
== Critères de qualité


[role="arc42help"]
****

.Contenu
Cette section contient tous les critères de qualité sous la forme d'un arbre de qualité avec des scénarios. Les plus importantes ont déjà été décrites au point 1.2 (objectifs de qualité).

Ici, vous pouvez également capturer des critères de qualité avec une priorité moindre,
qui n'entraîneront pas de risques élevés si elles ne sont pas entièrement satisfaites.

.Motivation
Étant donné que les critères de qualité auront une grande influence sur les décisions architecturales,
vous devez savoir, pour chaque partie prenante, ce qui est vraiment important pour elle,
ce qui est concret et mesurable.


.Informations supplémentaires

Voir https://docs.arc42.org/section-10/[Quality Requirements] dans la documentation arc42.

****

=== Arbre de qualité

[role="arc42help"]
****
.Contenu
L'arbre de qualité (tel que défini dans ATAM – Architecture Tradeoff Analysis Method) avec des scénarios de qualité/évaluation sous forme de feuilles.

.Motivation
L'arborescence avec les priorités permet d'avoir une vue d'ensemble d'un nombre parfois important de critères de qualité.

.Représentation
L'arbre de qualité est une vue d'ensemble des objectifs et des critères de qualité :

* raffinement arborescent du terme "qualité". Utiliser "qualité" ou "utilité" comme racine
* une carte mentale dont les principales branches sont les catégories de qualité

Dans tous les cas, l'arbre doit inclure des liens vers les scénarios de la section suivante.

****

=== Scénarios Qualité

[role="arc42help"]
****
.Contenu
Concrétisation des critères de qualité (parfois vagues ou implicites) à l'aide de scénarios Qualité.

Ces scénarios décrivent ce qui doit se passer lorsqu'un stimulus arrive au système.

Pour les architectes, deux types de scénarios sont importants :

* Les scénarios d'utilisation (également appelés scénarios d'application ou scénarios de cas d'utilisation) décrivent la réaction du système en cours d'exécution à un certain stimulus. Cela inclut également les scénarios qui décrivent l'efficacité ou la performance du système. Exemple : Le système réagit à la demande d'un utilisateur en une seconde.
* Les scénarios de changement décrivent une modification du système ou de son environnement immédiat. Exemple : Une fonctionnalité supplémentaire est mise en œuvre ou les exigences relatives à la modification d'un attribut Qualité.

.Motivation
Les scénarios concrétisent les exigences de qualité et permettent de mesurer ou de décider plus facilement si elles sont satisfaites.

En particulier lorsque vous souhaitez évaluer votre architecture à l'aide de méthodes telles que
ATAM, vous devez décrire vos objectifs qualité (voir section 1.2)
plus précisément à un niveau de scénarios qui peuvent être discutés et évalués.

.Représentation
Texte tabulaire ou libre.
****
