[[section-runtime-view]]
== Laufzeitsicht


[role="arc42help"]
****
.Inhalt
Diese Sicht erklärt konkrete Abläufe und Beziehungen zwischen Bausteinen
in Form von Szenarien aus folgenden Bereichen:

*  Wichtige Abläufe oder _Features_:
Wie führen die Bausteine der Architektur die wichtigsten Abläufe durch?
*  Interaktionen an kritischen externen Schnittstellen:
Wie arbeiten Bausteine mit Nutzern und Nachbarsystemen zusammen?
* Betrieb und Administration: Inbetriebnahme, Start, Stop.
* Fehler- und Ausnahmeszenarien

Anmerkung: Kriterium für die Auswahl der möglichen Szenarien (d.h. Abläufe) des Systems ist deren Architekturrelevanz.
Es geht nicht darum, möglichst viele Abläufe darzustellen, sondern eine angemessene Auswahl zu dokumentieren.


.Motivation
Sie sollten verstehen wie (Instanzen von) Bausteine(n) Ihres Systems ihre
jeweiligen Aufgaben erfüllen
und zur Laufzeit miteinander kommunizieren.

Nutzen Sie solche Szenarien in der Dokumentation hauptsächlich zur besseren
Kommunikation mit Stakeholdern, die statische Modelle
(z.B. Bausteinsicht, Verteilungssicht) weniger verständlich finden.


.Form
Für die Beschreibung von Szenarien gibt es zahlreiche Ausdrucksmöglichkeiten.
Nutzen Sie beispielsweise:

* Nummerierte Schrittfolgen oder Aufzählungen in Umgangssprache
* Aktivitäts- oder Flussdiagramme
* Sequenzdiagramme
* BPMN oder EPKs (Ereignis-Prozessketten)
* Zustandsautomaten
* ...

****

=== _<Bezeichnung Laufzeitszenario 1>_

*  <hier Laufzeitdiagramm oder Ablaufbeschreibung einfügen>
*  <hier Besonderheiten bei dem Zusammenspiel der Bausteine in diesem Szenario erläutern>

=== _<Bezeichnung Laufzeitszenario 2>_

...

=== _<Bezeichnung Laufzeitszenario n>_

...
