[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract) of requiremnents. Link to (hopefully existing) requirements documents (with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.
****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) goals for the architecture and/or constraints whose fulfillment is of highest importance to the major stakeholders. Goals that define the architecture’s quality could be:

* availability
* modifiability
* performance
* security
* testability
* usability

.Motivation
If you as an architect do not know how the quality of your work can be judged …

.Form
Simple tabular representation, ordered by priorities

.Background Information
*NEVER* start developing an architecture if these goals have not been put into writing and have not been signed by the major stakeholders.

[WARNING]
===========
We have endured projects lacking defined quality goals much too often.
We do not like to suffer, therefore we are by now highly convinced that
the few hours spent on collecting quality goals are well invested.
PH & GS.
===========

.Sources
The DIN/ISO 92000 Standard contains an extensive set of possible quality goals.Or use chapters 10 – 17 of the http://www.volere.co.uk[VOLERE template] as a starting point .
PH

****

=== Stakeholders

[role="arc42help"]
****
.Contents
A list of the most important persons or organizations that are affected by or can contribute to the architecture.

.Motivation
If you do not know the persons participating in or concerned with the project you may get nasty surprises later in the development process. Should your project manager maintain this list, make sure that all the people influencing the architecture are part of it.

.Form
Simple table with role names, person names, their knowledge as pertaining to architecture, their availability, etc.
.Stakeholders
[options="header",cols="<.<1,<.<2, <.<2"]
|===
|Role/Name|Goal/Boundaries|Expected Participation and Contribution
| The name or role of a stakeholder| Why will this stakeholder have an interest in the architecture? | what do you expect as a contribution
|===
****


