[[section-system-scope-and-context]]
== System Scope and Context

 
[role="arc42help"]
****
.Contents
System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners (neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
* Various context diagrams
* Lists of communication partners and their interfaces.
****


=== Business Context

[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces. Optinoally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders shoud understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communiations partners.

Alternatively (or additionally) you can use a table. The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.

****

=== Technical Context

[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation with I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces. 

.Form
E.g. UML deployment diagram describing channels to neighboring systems, together with a mapping table showing the relationships between channels and input/output.

****

=== External Interfaces

[role="arc42help"]
****
For many building blocks you can describe its interfaces directly in the black box template of the building block. For complex interfaces – and external interfaces are normally very complex – it is worth while to describe them in separate sections. Use the following interface template to guide you towards many questions that might be relevant for the interface.

.Interface Template
.

.Interface Template
[options="header", cols="<.<1,<.<3"]
|===
2+<| Interface ID
| Name| Name of the Interface
| Version | 
| Changes w.r.t. previous release |
| Who changed it and why? |
| Contact person(s) or organization |
|===

.Business Context of the Interface
.

.Business Processes
<Diagram or desciption of business processes relevant for this interface>

.Interface Data
<Description of interface data>

* Technical Context
* Form of interaction

.Requirements for the Interface
* ...

.Security Aspects
* ...

.Quantities
* Runtime
* Throughput/Volume
* Availability
* Logging
* Archiving

.Participating Resources
* ...

.Syntax: Data and Formats
* Data Formats
* Validity & Plausibility Rules
* Encoding, Character Sets
* Configuration data

.Syntax: Methods/Functions
* Check data

.Interface Process
* Logical and technical processes

.Semantics
* Side effects, consequences

.Technical Infrastructure
* Technical protocols

.Error and Exception Handling
* ...

.Constraints and Assumptions
* Access Rights
* Temporal constraints
* Parallel Access
* Preconditions for using the interface

.Operating the Interface
* ...

.Meta Information for the Interface
* Person in charge
* Costs of using the interface
* Organizational Issues
* Versioning

.Examples of Using the Interface
* Sample data
* Sample flows and interactions
* Programming Examples

.External Interface 2
<insert interface template>

.External Interface 3
<insert interface template>

. ...

.External Interface n
<insert interface template>

****

