[[section-deployment-view]]


== Deployment View

[role="arc42help"]
****
.Content
This view describes:

 1. the technical infrastructure used to execute your system, with infrastructure elements like geographical location, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. the mapping of (software) building blocks to that infrastructure 

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environment.

Especially docuemnt the deployment view when your software is executed as distributed system with more then one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to cover those aspects of the infrastructure that are relevant for the deployment of your building blocks. Hardware architects can go beyond that and describe the infrastructure to any level of detail they need to capture. 

.Motivation
Software does not run without infrastructure. The underlying infrastructure can and will influence your system and/or cross-cutting concepts. Therefore, you need to know the infrastructure. 

.Form

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams, when your infrastructure is more comnplex.
+
The highest level deployment diagram maybe is already contained in section 3.2. as technical context with your own infrastructure as ONE black-box. In this section you will zoom into this black box using additional deployment diagrams. 

* Falls Ihre Infrastruktur-Stakeholder andere Diagrammarten bevorzugen,
die Prozessoren und Kanäle zeigen, sind die hier ebenfalls einsetzbar.

****

=== Infrastruktur Ebene 1


[role="arc42help"]
****
An dieser Stelle beschreiben Sie (als Kombination von Diagrammen mit
Tabellen oder Texten):

*  die Verteilung des Gesamtsystems auf
mehrere Standorte, Umgebungen, Rechner, Prozessoren oä.
sowie die physischen Verbindungskanäle zwischen diesen,
*  wichtige Begründungen für dieser Verteilungsstruktur,
* Qualitäts- und/oder Leistungsmerkmale dieser Infrastruktur,
*  Zuordnung von Softwareartefakten zu Bestandteilen der Infrastruktur

Für mehrere Umgebungen oder alternatives Deployment
kopieren Sie diesen Teil von arc42 für alle wichtigen Umgebungen.

****

_**<Übersichtsdiagramm>**_

Begründung::

_<Erläuternder Text>_

Qualitäts- und/oder Leistungsmerkmale::

_<Erläuternder Text>_

Zuordnung von Bausteinen zu Infrastruktur::
_<Beschreibung der Zuordnung>_


=== Infrastruktur Ebene 2

[role="arc42help"]
****
An dieser Stelle können Sie den inneren Aufbau
(einiger) Infrastrukturelemente aus Ebene 1 beschreiben.

Für jedes Infrastrukturelement kopieren Sie die Struktur aus Ebene 1.

****

==== _<Infrastrukturelement 1>_

_<Diagramm + Erläuterungen>_

==== _<Infrastrukturelement 2>_

_<Diagramm + Erläuterungen>_

...

==== _<Infrastrukturelement n>_

_<Diagramm + Erläuterungen>_
