:numbered!:

[appendix]
[[contributions]]
== Acknowledgements and collaborations


arc42 originally envisioned by
http://b-agile.de[Dr. Peter Hruschka] and
http://gernotstarke.de[Dr. Gernot Starke].


Sources::
We maintain arc42 in _asciidoc_ format at the moment, hosted in
https://github.com/aim42/aim42[GitHub under the aim42-Organisation].

Issues::
We maintain a list of
https://github.com/arc42/arc42-template/issues[open topics and bugs].

We are looking forward to your corrections and clarifications! Please fork
the repository mentioned over this lines and send us a _pull request_!

=== Collaborators
We are very thankful and acknowledge the support and help provided
by all active and former collaborators, uncountable (anonymous) advisors,
bug finders and users of this method.


==== Currently active

* Gernot Starke
* Stefan Zörner
* Markus Schärtel
* Ralf D. Müller
* Peter Hruschka
* Jürgen Krey


==== Former collaborators
(in alphabetical order)

* Anne Aloysius
* Matthias Bohlen
* Karl Eilebrecht
* Manfred Ferken
* Phillip Ghadir
* Carsten Klein
* Prof. Arne Koschel
* Axel Scheithauer
