ifndef::imagesdir[:imagesdir: ../images]

[[section-quality-scenarios]]
== Quality Requirements


ifdef::arc42help[]
[role="arc42help"]
****

.Content
This section contains all relevant quality requirements. 
The most important of these requirements  have already been described in section 1.2. (quality goals), therefore they should only be referenced.

Here (in section 10) you can also capture quality requirements with lesser priority, which will not create high risks when they are not fully achieved.

.Motivation
Since quality requirements will have a lot of influence on architectural decisions you should know  what is really important for every stakeholder, in a specific and measurable way.


.Further Information

* See https://docs.arc42.org/section-10/[Quality Requirements] in the arc42 documentation.
* See the extensive https://quality.arc42.org[extensive Q42 quality model].

****
endif::arc42help[]


=== Quality Requirements Overview

ifdef::arc42help[]
[role="arc42help"]
****

.Content
An overview or summary of quality requirements. 


.Motivation
Often we encounter dozens (or even hundreds) of detailed quality requirements. 
In this overview section you should try to summarize, e.g. by describing categories or topics (as suggested by ISO 25010:2023 or https://quality.arc42.org[Q42])
Refer to the detailed requirements which are described with precise metrics or acceptance criteria in the following section.

If your descriptions are specific enough and measurable, you may skip section 10.2.

.Form
Alternatively, you may use a mindmap to structure these quality requirements.
In literature, the idea of a _quality attribute tree_ has also been described, which puts the generic term "quality" as the root and uses a tree-like refinement of the term "quality". 
[Bass+23] introduced the term "Quality Attribute Utility Tree" for this purpose.



****
endif::arc42help[]


=== Quality Scenarios

ifdef::arc42help[]
[role="arc42help"]
****

.Content
Quality scenarios 
Scenarios make quality requirements concrete and allow to decide whether they are fulfilled (in the sense of acceptance criteria).
Ensure that your scenarios are specific and measurable.



Two kinds of scenarios are especially useful:

* _Usage scenarios_ (also called application scenarios or use case scenarios) describe the system’s runtime reaction to a certain stimulus. 
This also includes scenarios that describe the system’s efficiency or performance. 
Example: The system reacts to a user’s request within one second.
* _Change scenarios_ describe a modification of the system or of its immediate environment. 
Example: Additional functionality is implemented or requirements for a quality attribute change, and the effect or duration of the change is measured.


.Form

Typical information for detailed scenarios include the following:

In short form (favoured in the Q42 model):

* Context/Background: What kind of system or component, what is the envirionment or situation?
* Source/Stimulus: Who or what initiates or triggers a behaviour, reaction or action.
* Metric/Acceptance Criteria: A response including a _measure_ or _metric_


The long form of scenarios (favoured by the SEI and [Bass+23]):

* Source: The entity (user, system, or event) that initiates the scenario.
* Stimulus: The triggering event or condition the system must address.
* Environment: The operational context or condition under which the system experiences the stimulus.
* Artifact: The portion or component of the system affected by the stimulus.
* Response: The outcome or behavior the system exhibits in reaction to the stimulus.
* Response Measure: The criteria or metric by which the system’s response is evaluated.


.Examples
See https://quality.arc42.org[the Q42 quality model website] for detailes examples of quality requirements.

.Further Information

* Len Bass, Paul Clements, Rick Kazman: "Software Architecture in Practice", 4th Edition, Addison-Wesley, 2021.

****


endif::arc42help[]
