ifndef::imagesdir[:imagesdir: ../images]

[[section-quality-scenarios]]
== Quality Requirements


ifdef::arc42help[]
[role="arc42help"]
****

.Content
This section contains all relevant quality requirements with (precise) metrics, so their achievement can be objectively decided.
The most important of these requirements  have already been described in section 1.2. (quality goals)

In this section 10 you can also capture quality requirements with lesser priority, which will not create high risks when they are not fully achieved.

.Motivation
Since quality requirements will have a lot of influence on architectural decisions you should know for every stakeholder what is really important to them, in a specific and measurable way.

.Form
Use a table or list, at best sorted by priority.
Alternatively, you may use a mindmap to structure these quality requirements.
In literature, the idea of a _quality attribute tree_ has also been described, which puts the generic term "quality" as the root and uses a tree-like refinement of the term "quality". 


Scenarios make quality requirements concrete and allow to decide whether they are fulfilled.
Two kinds of scenarios are especially useful:

* _Usage scenarios_ (also called application scenarios or use case scenarios) describe the system’s runtime reaction to a certain stimulus. 
This also includes scenarios that describe the system’s efficiency or performance. 
Example: The system reacts to a user’s request within one second.
* _Change scenarios_ describe a modification of the system or of its immediate environment. 
Example: Additional functionality is implemented or requirements for a quality attribute change, and the effect or duration of the change is measured.

XXX: Better description of scenarios. 

.Further Information

See https://docs.arc42.org/section-10/[Quality Requirements] in the arc42 documentation.

****
endif::arc42help[]



