ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Представление времени выполнения

[role="arc42help"]
****
.Содержание
Представление времени выполнения описывает конкретное поведение и взаимодействие строительных блоков системы в виде сценариев из следующих областей:

* важные варианты использования или функции: как строительные блоки их выполняют?
* взаимодействия на критических внешних интерфейсах: как строительные блоки взаимодействуют с пользователями и соседними системами?
* эксплуатация и администрирование: запуск, запуск, остановка
* сценарии ошибок и исключений

Примечание: Основным критерием выбора возможных сценариев (последовательностей, рабочих процессов) является их *архитектурная релевантность*.
*Не* нужно без надобности описывать большое количество сценариев.
Вам лучше задокументировать репрезентативный выбор.

.Мотивация
Вы должны понимать, как (экземпляры) строительных блоков вашей системы выполняют свою работу и взаимодействуют во время выполнения.
В основном вы будете фиксировать сценарии в своей документации, чтобы сообщить о своей архитектуре заинтересованным сторонам, которые менее склонны или не способны читать и понимать статические модели (представление стандартных блоков, представление развертывания).

.Форма
Существует множество обозначений для описания сценариев, например.

* пронумерованный список шагов (на естественном языке)
* диаграммы деятельности (activity diagrams) или блок-схемы
* диаграммы последовательности (sequence diagrams)
* BPMN или EPC (цепочки обработки событий)
* конечные автоматы
* ...

.Дальнейшая информация
Смотри https://docs.arc42.org/section-6/[Представление времени выполнения] в документации arc42.

****

=== <Сценарий времени выполнения 1>

* _<вставьте диаграмму выполнения или текстовое описание сценария>_
* _<вставьте описание важных аспектов взаимодействия между экземплярами стандартных блоков, изображенных на этой диаграмме.>_

=== <Сценарий времени выполнения 2>

=== ...

=== <Сценарий времени выполнения n>
