ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]
== Представления развертывания

[role="arc42help"]
****
Представление развертывания описывает:

1. техническую инфраструктуру, используемую для работы вашей системы, с элементами инфраструктуры, такими как географические местоположения, среды, компьютеры, процессоры, каналы и сетевые топологии, а также другие элементы инфраструктуры и

2. сопоставление строительных блоков (программного обеспечения) с этими элементами инфраструктуры.

Часто системы выполняются в разных средах, например. среда разработки, тестовая среда, продакшн.
В таких случаях вы должны задокументировать все соответствующие среды.

Особенно важно задокументировать представление развертывания, если ваше программное обеспечение выполняется в виде распределенной системы с более чем одним компьютером, процессором, сервером или контейнером; или когда вы проектируете и создаете свои собственные аппаратные процессоры и микросхемы.

С точки зрения программного обеспечения достаточно зафиксировать только те элементы инфраструктуры, которые необходимы для демонстрации развертывания ваших строительных блоков.
Архитекторы аппаратного обеспечения могут пойти дальше и описать инфраструктуру с любым уровнем детализации, который им необходим.

.Мотивация
Программное обеспечение не работает без аппаратного обеспечения.
Эта базовая инфраструктура может и будет влиять на систему и/или некоторые сквозные (сквозные) концепции.
Поэтому необходимо знать инфраструктуру.

.Форма
Возможно, схема развертывания самого высокого уровня уже содержится в разделе 3.2. в виде технического контекста с собственной инфраструктурой, описанного ОДНИМ черным ящиком.
В этом разделе можно раскрыть этот черный ящик, используя дополнительные диаграммы развертывания:

* UML предлагает диаграммы развертывания, чтобы выразить это представление.
Используйте его, возможно, с вложенными диаграммами, в случае если ваша инфраструктура более сложна.
* Если заинтересованные стороны (связанные с аппаратным обеспечением) предпочитают другие виды диаграмм, а не диаграмму развертывания, позвольте им использовать любой вид, способный отображать узлы и каналы инфраструктуры.

.Дальнейшая информация
Смотри https://docs.arc42.org/section-7/[Представление развертывания] в документации arc42.

****

=== Инфраструктурный уровень 1

[role="arc42help"]
****

Опишите (обычно в комбинации диаграмм, таблиц и текста):

* распределение системы по нескольким местоположениям, средам, компьютерам, процессорам и т. д., а также физическим соединениям между ними
* важные обоснования или мотивы для этой структуры развертывания
* характеристики качества и/или производительности этой инфраструктуры
* сопоставление программных артефактов с элементами этой инфраструктуры

Для нескольких сред или альтернативных развертываний скопируйте и адаптируйте этот раздел arc42 для всех соответствующих сред.
****

_**<Обзорная диаграмма>**_

Мотивация::

_<объяснение в текстовом виде>_

Характеристики качества и/или производительности::

_<объяснение в текстовом виде>_

Сопоставление строительных блоков с инфраструктурой::
_<описание сопоставления>_

=== Инфраструктурный уровень 2

[role="arc42help"]
****
Сюда можно включить внутреннюю структуру (некоторых) Инфраструктурных элементов уровня 1.

Пожалуйста, скопируйте структуру уровня 1 для каждого выбранного элемента.
****

==== _<Инфраструктурный элемент 1>_

_<диаграмма + объяснение>_

==== _<Инфраструктурный элемент 2>_

_<диаграмма + объяснение>_

...

==== _<Инфраструктурный элемент n>_

_<диаграмма + объяснение>_
