[[section-system-scope-and-context]]

== Kontextabgrenzung


[role="arc42help"]
****
.Inhalt
Die Kontextabgrenzung grenzt das System von allen Kommunikationspartner (Nachbarsysteme und Benutzerrollen) ab. Sie legt damit die externen Schnittstellen fest. Differenzieren Sie fachlichen Kontext (fachliche Ein- und Ausgaben) und technischen Kontext (Kanäle, Protokolle, Hardware), falls nötig.


.Motivation
Die fachlichen und technischen Schnittstellen zu Kommunikationspartnern gehören zu den kritischsten Aspekten eines Systems. Stellen Sie rechtzeitig sicher, dass Sie diese komplett verstanden haben.

.Form
*  Diverse Kontextdiagramme
*  Listen von Kommunikationspartnern mit deren Schnittstellen.
****


=== Fachlicher Kontext

[role="arc42help"]
****
.Inhalt
Festlegung aller footnote:[alle,Zwar sind wir an vielen Stellen zu Pragmatismus bereit – hier
jedoch bestehen wir auf der vollständigen Auflistung aller *(a-l-l-e-r)* Kommunikationspartner.
Zu viele Projekte sind daran gescheitert, dass sie ihre Nachbarn nicht kannten :-(]
Kommunikationspartner (Menschen, IT-Systeme, ...) mit Erklärung der fachlichen Ein- und Ausgabedaten oder Schnittstellen. Zusätzlich bei Bedarf fachliche Datenformate
oder Protokolle der Kommunikation mit den Nachbarsystemen, sofern diese Informationen nicht bei den spezifischen Bausteinen erläutert werden.

.Motivation
Alle Beteiligten müssen verstehen, welche fachlichen Informationen mit der Umwelt ausgetauscht werden.


.Form
Alle Diagrammarten, die das System als Black Box
darstellen und die fachlichen Schnittstellen zu den Nachbarn (mehr oder weniger ausführlich) beschreiben.

Alternativ oder ergänzend können Sie eine Tabelle verwenden. Der Titel gibt den Namen Ihres Systems wieder; die drei Spalten sind: Kommunikationspartner, Eingabe, Ausgabe.
****


=== Technischer Kontext

[role="arc42help"]
****
.Inhalt
Technische Schnittstellen (Kanäle, Übertragungsmedien) zwischen dem System und seiner Umwelt. Zusätzlich eine Abbildung, welche fachlichen Ein- und Ausgaben über welche technische Kanäle fließen.


.Motivation
Die Kenntnis der technischen Schnittstellen des Systems zu seiner Umgebung ist für viele Stakeholder, insbesondere Infrastruktur- oder Hardwareentwickler sowie Administratoren und Betreiber, wichtig für viele Entscheidungen.


.Form
Beispielsweise UML Deployment-Diagramme mit den Kanälen zu Nachbarsystemen, begleitet von einer Tabelle, die Kanäle auf Ein-/Ausgaben abbildet.

****

