= arc42 Template Requirements
:toc:
:author: Gernot Starke
:email: gernot.starke@innoq.com
:date: June 10th 2014
:revision: Version 0.2


:numbered:


// some url's

:confluence-link: https://www.atlassian.com/software/confluence[Confluence (C)]
:asciidoc-link: http://asciidoctor.org[AsciiDoctor]
:gradle-link: http://gradleware.org[Gradle]
:stackoverflow-link: http://stackoverflow.com/tags/arc42/info[Stackoverflow]
:nabble-link: http://arc42-discussion.1007769.n3.nabble.com/[forum]

:peter-link: http://b-agile.de[Peter Hruschka]
:gernot-link: http://gernotstarke.de[Gernot Starke]


[NOTE]
====
Within the following text, the "arc42 template" shall be abbreviated +arc42+
====


== Kind of Requirements

[horizontal]
<<goals, Goals:>>:: the fundamentals

<<usage, Usage:>>:: Stakeholders and their perspective on +arc42+.

<<formats, Formats:>>:: Technical formats, like MS-Word (C) (docx), pdf, html or others.

<<toolchains, Toolchains:>>:: Tools supported to apply +arc42+ or maintain <<formats>> or <<versions>>

<<versions, Versions:>>:: Content versions, e.g. the pure structure, with help content, with examples etc.
Versions can be available in various <<formats>>.



[[goals]]
== Goals

====
+arc42+ is well-suited for software architecture documentation and communication.
It is free, both for commercial or open-source projects or systems.
====

+arc42+ shall be:

. *Agnostic* towards
.. development process, +arc42+ can be used in iterative, strict,
formal or informal processes
.. applied technologies of the system
(programming languages, frameworks, operating systems)
.. system domain
.. kind of system (i.e. interactive, batch, server/backend, mobile, client/server etc.)
.. system size, +arc42+ shall support small to medium systems without modification
   (up to approx 1 million LOC)
.. system lifecycle phase: it can be used a-priori and a-posteriori
for planning, designing or describing systems.

. *Easily usable*. It shall
.. contain clear and helpful documentation
.. provide various examples
.. be available in various
   ** <<formats, _formats_>> (e.g. MS-Word (C), pdf, {confluence-link}, etc.)
   ** <<versions, _versions_>> (e.g. without help, with help included, with examples included etc.)
   ** _languages_, at least English and German
.. have low requirements to use in the supported <<toolchains, toolchains>>

. *Flexible*
.. Users (software architects and developers) can adapt and modify +arc42+ towards
their needs.
.. +arc42+ can be used with different <<toolchains, toolchains>>.


=== Non-Goals

+arc42+ does not

* address safety critical systems
* replace requirements documentation
* replace formal technical documentation


[[usage]]
== Usage Requirements

=== Users and Roles

[horizontal]
User:: works on a software system, needs to communicate or document
architectural aspects (decisions, structures, concepts, requirements etc) of
this system.

Contributor:: support and improve <<formats, template formats>>,
<<versions>>, <<toolchains, toolchains>> and/or content. Help to answer questions on
{stackoverflow-link} or {nabble-link} or fix bugs.

Founders:: {peter-link} and {gernot-link}
ensure conceptual integrity of the arc42 ecosystem.


=== Use Cases

[[document-use-case]]
. *Document*: use +arc42+ to document or communicate a software architecture.
This use-case is supported by the available
<<out_formats, output formats>> (e.g. docx (C), html, asciidoc)

. *Maintain*: work on the arc42 ecosystem by either
  ** adding <<formats>>, <<versions>> or examples
  ** improving the maintenance infrastructure


[[formats]]
== Required Formats


[[out_formats]]
=== Output Formats
Output formats are used to document existing or planned software systems
with the <<document-use-case, documentation use-case>>.

+arc42+ shall support the following output formats:

. Microsoft (C) Word docx format, single file, including
  ** table-of-contents
  ** header and footer, optionally containing logo

. {confluence-link} format, providing the complete template as _space_
  ** supporting Confluence versions from 3.x up to the latest versions.

. {asciidoc-link} format (modularized), together with build-system to generate/compile
results into html/pdf.

. html format, especially the versions including help text and samples

. pdf format, restricted to version including help text and samples


=== Maintenance Format

. Content and structure of +arc42+ shall be maintained in AsciiDoc.
  ** All required output formats shall be generated from this.

Maintenance format shall strive for low redundancy and follow the DRY-principle.



[[toolchains]]
== Supported Toolchains

. Word (C) or similar text processors, combined with any graphical tool for diagrams.
. UML modeling tool, either for diagrams-only or for the complete documentation.
. Wikis (e.g. {confluence-link}), combined with any graphical tool for diagrams.
. Text-based formats (like {asciidoc-link}), combined with any graphical tool for diagrams.


For all toolchains, requirements for its application shall be kept low.



[[versions]]
== Required Versions

+arc42+ shall be supplied in the following versions:

. *Skeleton* version, containing
  ** all headers
  ** appropriate title-page with formal section (name-of-system, authors etc.)
  ** table-of-contents
  ** plain structure without help text or samples
  ** placeholders for substructures, like black- and whitebox templates
  ** empty tables, e.g. for stakeholder, quality-goals, external interfaces etc.

. *With-Help* version, containing the complete skeleton, plus
  ** help texts for all chapters and sections
  ** explanations

. Multiple *samples* version, containing the complete skeleton, plus example diagrams,
tables for every chapter and section.


== Open Source Requirements

* +arc42+ is free and open-source, under a liberal Creative-Commons Sharealike license.
It can be used in arbitrary projects for arbitrary systems without any fees or
restrictions. Please note - there is no guarantee!

* It is hosted and maintained on GitHub.



== Technical Constraints


* Generation of formats shall be automated as much as possible
* Build of <<out_formats, output formats>> can be done with
  ** {gradle-link} (first priority)
  ** others, if demand arises
