== How to use asc42 with confluence

NOTE: for more information about confluence, see http://www.atlassian.com/confluence

If you want to use confluence as master for your asc42 documentation, simply use the generated confluence 
space which can found at http://confluence.arc42.org/display/LANDINGZON/landing+zone .

If you want to use confluence not as master but for publishing your documentation, check the 
link:export2confluence.adoc[export2confluence]-module.

New version of confluence are often released and newer versions are often not able to import spaces from older 
versions. So it is very likely that you will not be able to import the space referenced above. The solution for this 
problem is to install the confluence version from which the space has been exported and upgrade it to your current 
version. From this one, you can re-export the space.

Another problem which you might face is that a page title has to be unique in a confluence space. So, if you want to 
document two projects in confluence with this template, you either have to use two spaces or you have to rename
all pages. If you have only one space available because of some contraints of your system, you can use the 
link:export2confluence.adoc[export2confluence]-module to export the original arc42 AsciiDoc template with a prefix
to your space.
