== export2confluence

This module is an example on how AsciiDoc documentation can be exported to a wiki.

When you write your documentation in AsciiDoc, the main use case for exporting it to a wiki is probably to expose 
it to a bigger audience and collect feedback through the comment or discussion functionality of the chosen wiki.
This means that it is important to set the resulting pages to read-only in order to avoid having two sources of 
documentation. Maybe a later version of the script could sync changes back from wiki to AsciiDoc, but currently 
it is not likely that this will be soon.

==== Why do we use www.atlassian.com/confluence[confluence] for this example?

- the team has some experience with confluence
- confluence comes with a nice, easy to use REST API
- you can set confluence pages to read-only and they still can be commented

==== How does the export work?

First, the internal format of the wiki has to be identified, because this will be the target format for the first 
AsciiDoc transformation. In case of confluence, the internal format is a subset of HTML. Other wikis are likely to 
use some kind of markdown as format.

The export2confluence module uses the HTML output generated from the original AsciiDoc documents. This HTML is then
analyzed with the http://jsoup.org[jsoup] HTML parser in order to break it down into sub pages.

Each of the sup pages then has to be analyzed for compatibility with confluence and will be transformed if necessary.

Afterwards, the script tries to find out if the new page is equal to the possibly already existing one. If so, the 
page will be skipped, but if the page is different or even does not exist yet, it will be send to confluence as new
content. This is an important step because confluence will store each page submission - even if the page hasn't 
changed - in the history of that page. Unfortunately, this will render the history useless.


